apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-node-chrome-sample
  labels:
    app: selenium-node-chrome-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-node-chrome-sample
  template:
    metadata:
      labels:
        app: selenium-node-chrome-sample
    spec:
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      containers:
      - name: selenium-node-chrome-sample
        image: selenium/node-chrome-debug:3.11.0-dysprosium
        ports:
          - containerPort: 5555
            name: port1
          - containerPort: 5900
            name: portvnc
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
        env:
          - name: HUB_HOST
            value: "selenium-hub-sample"
          - name: HUB_PORT
            value: "4444"
        resources:
          limits:
            memory: "1500Mi"
            cpu: ".5"
      nodeSelector:
        selenium-chrome-node: "true"
